// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function sumTo(n) {
  var _i = n;
  var _sum = 0;
  while(true) {
    var sum = _sum;
    var i = _i;
    if (i === 0) {
      return sum;
    }
    _sum = sum + i | 0;
    _i = i - 1 | 0;
    continue ;
  };
}

function swap(param) {
  return [
          param[1],
          param[0]
        ];
}

var chars = [
  "a",
  "b"
];

var numbers = [
  1,
  2
];

var mix = [
  "a",
  1
];

console.log(swap(chars));

console.log(swap(numbers));

console.log(swap(mix));

exports.sumTo = sumTo;
exports.swap = swap;
exports.chars = chars;
exports.numbers = numbers;
exports.mix = mix;
/*  Not a pure module */
