// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, World!");

var y = {
  contents: 7
};

console.log(7);

console.log(y);

y.contents = y.contents + 1 | 0;

console.log(7);

console.log(y);

console.log(5 + 4.5);

console.log(9);

var hello = "Hello, ";

var name = "Tyyago";

console.log("Hello, Tyyago");

console.log("Hello, Tyyago");

console.log(true);

console.log(true);

console.log(false);

console.log(true !== false);

var point = {
  x: 20,
  y: 30
};

var another = {
  x: 5,
  y: 30
};

var anotherPoint = {
  x: 20,
  y: 5
};

console.log(point);

console.log(another);

console.log(anotherPoint);

var arr = [
  2,
  5,
  6,
  8
];

var tuple = [
  "Tyyago",
  18,
  1.80
];

console.log(arr);

console.log(tuple);

function five(param) {
  return 5;
}

function sum(x, y) {
  return x + y | 0;
}

function increment(param) {
  return 1 + param | 0;
}

function decrement(param) {
  return -1 + param | 0;
}

console.log(12);

console.log(1);

console.log(-1);

function superComplexFunction(x, y) {
  var a = Math.imul(x, y);
  if (a > 25) {
    return "high value";
  } else {
    return "low value";
  }
}

var l = superComplexFunction(5, 5);

var h = superComplexFunction(6, 10);

console.log(l);

console.log(h);

for(var c = 0; c <= 15; ++c){
  console.log(c);
}

for(var c$1 = 15; c$1 >= 0; --c$1){
  console.log(c$1);
}

var x = 7;

var i = 5;

var f = 4.5;

var truth = true;

var lie = false;

exports.x = x;
exports.y = y;
exports.i = i;
exports.f = f;
exports.hello = hello;
exports.name = name;
exports.truth = truth;
exports.lie = lie;
exports.point = point;
exports.another = another;
exports.anotherPoint = anotherPoint;
exports.arr = arr;
exports.tuple = tuple;
exports.five = five;
exports.sum = sum;
exports.increment = increment;
exports.decrement = decrement;
exports.superComplexFunction = superComplexFunction;
exports.l = l;
exports.h = h;
/*  Not a pure module */
