// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function sum_if(n, sum, condition) {
  if (Curry._1(condition, n)) {
    return n + sum | 0;
  } else {
    return sum;
  }
}

function checkIsMultiplier(n) {
  if (n % 3 === 0) {
    return true;
  } else {
    return n % 5 === 0;
  }
}

function sumTo(limit) {
  var _n = limit - 1 | 0;
  var _sum = 0;
  while(true) {
    var sum = _sum;
    var n = _n;
    if (n === 0) {
      return sum;
    }
    _sum = sum_if(n, sum, checkIsMultiplier);
    _n = n - 1 | 0;
    continue ;
  };
}

console.log(sumTo(10));

console.log(sumTo(1000));

exports.sum_if = sum_if;
exports.checkIsMultiplier = checkIsMultiplier;
exports.sumTo = sumTo;
/*  Not a pure module */
