// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("rescript/lib/js/string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function isPalindromic(n) {
  var normal = String(n);
  var reverse = Belt_Array.reduce(Belt_Array.reverse(normal.split("")), "", (function (i, a) {
          return i + a;
        }));
  return $$String.equal(normal, reverse);
}

function largestPalindromic(param) {
  var _x = 999;
  var _y = 999;
  while(true) {
    var y = _y;
    var x = _x;
    if (x < 800) {
      return ;
    }
    if (y < 800) {
      _y = 999;
      _x = x - 1 | 0;
      continue ;
    }
    var n = Math.imul(x, y);
    if (isPalindromic(n)) {
      console.log("(" + String(x) + ", " + String(y) + ") -> " + String(n));
    }
    _y = y - 1 | 0;
    continue ;
  };
}

largestPalindromic(undefined);

exports.isPalindromic = isPalindromic;
exports.largestPalindromic = largestPalindromic;
/*  Not a pure module */
