// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

function fn(lower, upper) {
  var _n = 20;
  while(true) {
    var n = _n;
    var length = (upper - lower | 0) + 1 | 0;
    var mods = Belt_Array.makeBy(length, (function(n){
        return function (i) {
          return Caml_int32.mod_(n, i + 1 | 0) === 0;
        }
        }(n)));
    var hasSomeFalse = Belt_Array.some(mods, (function (e) {
            return !e;
          }));
    if (!hasSomeFalse) {
      return n;
    }
    _n = n + 1 | 0;
    continue ;
  };
}

console.log(fn(1, 20));

exports.fn = fn;
/*  Not a pure module */
