// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Pervasives = require("rescript/lib/js/pervasives.js");

function intExp(a, b) {
  return Math.pow(a, b) | 0;
}

function makeNumbersArray(n) {
  return Belt_Array.makeBy(n, (function (i) {
                return i + 1 | 0;
              }));
}

function squareNumbers(arr) {
  return Belt_Array.map(arr, (function (n) {
                return Math.pow(n, 2) | 0;
              }));
}

function findDifference(n) {
  var numbers = makeNumbersArray(n);
  var sumOfSquare = Belt_Array.reduce(squareNumbers(numbers), 0, (function (a, b) {
          return a + b | 0;
        }));
  var a = Belt_Array.reduce(numbers, 0, (function (a, b) {
          return a + b | 0;
        }));
  var squareOfSum = Math.pow(a, 2) | 0;
  return Pervasives.abs(sumOfSquare - squareOfSum | 0);
}

console.log(findDifference(100));

exports.intExp = intExp;
exports.makeNumbersArray = makeNumbersArray;
exports.squareNumbers = squareNumbers;
exports.findDifference = findDifference;
/*  Not a pure module */
