// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function is_even(n) {
  return n % 2 === 0;
}

function calculate_next(n) {
  if (is_even(n)) {
    return n / 2 | 0;
  } else {
    return Math.imul(3, n) + 1 | 0;
  }
}

function generate_sequence(start) {
  var _seq = [start];
  var _i = 0;
  while(true) {
    var i = _i;
    var seq = _seq;
    var curr = Belt_Array.getExn(seq, i);
    var next = calculate_next(curr);
    var arr = Belt_Array.concat(seq, [next]);
    if (next === 1) {
      return [
              arr,
              i + 2 | 0
            ];
    }
    _i = i + 1 | 0;
    _seq = arr;
    continue ;
  };
}

function gen_all(lower, upper) {
  var _i = lower;
  var _big = [
    [],
    0,
    0
  ];
  while(true) {
    var big = _big;
    var i = _i;
    if (i === upper) {
      return big;
    }
    var seq = generate_sequence(i);
    var y = seq[1];
    var biggest = y > big[1] ? [
        seq[0],
        y,
        i
      ] : big;
    _big = biggest;
    _i = i + 1 | 0;
    continue ;
  };
}

exports.is_even = is_even;
exports.calculate_next = calculate_next;
exports.generate_sequence = generate_sequence;
exports.gen_all = gen_all;
/* No side effect */
